#!/usr/bin/env node
/**
 * Writes `dist/sw.js` after a build.
 *
 * ## Why this is generated rather than written by hand
 *
 * Vite hashes every asset filename, so the list of things to precache is only
 * known once the build has run. A hand-written service worker would either
 * have to fetch a manifest at runtime - one more request that can itself go
 * stale - or guess, and a service worker that guesses wrong serves half an
 * application forever.
 *
 * ## Why not a plugin
 *
 * `vite-plugin-pwa` would do this and more. What it brings with it is Workbox,
 * which is a larger dependency than the ~90 lines below and answers questions
 * this app does not have: it is static, it has no runtime API, and its assets
 * are content-hashed. The whole caching policy is two rules.
 *
 * ## The update problem
 *
 * A stale cache serving last month's rules is worse than no cache, so:
 *
 *   - The cache name carries a hash of the precache list. Any deploy that
 *     changes any asset changes the name, so the new worker fills a fresh
 *     cache and `activate` deletes every older one. Nothing is ever partly
 *     updated.
 *   - The new worker does **not** call `skipWaiting()` on its own. Swapping
 *     assets under a running page can hand it a chunk from a different build.
 *     It waits, the app notices and offers a reload, and the swap happens when
 *     the reader says so.
 *   - Navigations are network-first. The cached page is the offline fallback,
 *     not the default, so a visitor who is online is never a deploy behind.
 */
import { createHash } from 'node:crypto';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// fileURLToPath, not `.pathname`: the latter is `/C:/...` on Windows, which
// fs cannot open, and the failure reads as "no dist/" on a dist that exists.
const DIST = fileURLToPath(new URL('../dist/', import.meta.url));

/** Every emitted file, as a path relative to `dist/`. */
async function walk(dir, prefix = '') {
  const out = [];
  for (const entry of await readdir(join(DIST, dir), { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await walk(join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

const files = (await walk('.').catch(() => null)) ?? [];
if (!files.length) {
  console.error('No dist/ - run `npm run build` first.');
  process.exit(1);
}

/*
  What goes in the cache.

  `index.html` is included so the app opens with no network at all. The rules
  text chunk is included too: it is 524 kB and lazily loaded, so a visitor who
  never opened a description would otherwise find that the one thing needing
  the network is the thing they wanted at a table with no signal. Caching it
  up front is the whole point of caching for offline use.

  `sw.js` itself is excluded - a worker that caches itself is how a bad worker
  becomes permanent.
*/
const precache = files
  .filter((file) => file !== 'sw.js' && !file.endsWith('.map'))
  .sort();

/*
  The two invariants worth failing a build over, checked here rather than in a
  unit test because they are properties of the *emitted* list and nothing else
  can see it.

  A worker that precaches itself can never be replaced by a newer one, since
  the browser would be served the old copy when it goes to check. And a
  precache without `index.html` is an offline mode that cannot open the app -
  every asset present, nothing to load them from.
*/
if (precache.includes('sw.js')) {
  console.error('sw.js is in its own precache list - it could never be updated.');
  process.exit(1);
}
if (!precache.includes('index.html')) {
  console.error('index.html is missing from the precache - the app could not open offline.');
  process.exit(1);
}

/*
  The build's identity: change anything that ships and this changes, which
  renames the cache and makes the old one garbage on the next activate.

  Contents rather than filenames. Most assets are content-hashed, so their
  names would be enough for them - but `index.html`, `manifest.webmanifest`
  and the icons keep the same name forever. Hashing the list of names alone
  leaves a deploy that changes only those with the old cache still live, so an
  offline visitor keeps the old page indefinitely. Reading the bytes costs
  milliseconds on a build and removes the whole class of problem.
*/
const digest = createHash('sha256');
for (const path of precache) {
  digest.update(path);
  digest.update(await readFile(join(DIST, path)));
}
const buildId = digest.digest('hex').slice(0, 12);

const sw = `/*
  Generated by scripts/build-sw.mjs. Do not edit dist/sw.js - edit the script.

  Build ${buildId}, ${precache.length} files.
*/
const CACHE = 'forge-and-fate-${buildId}';

/*
  \`ignoreVary\` is not optional here, and the reason is worth writing down
  because the failure is silent and total.

  A precached entry is stored from a request this worker made, which carries no
  \`Origin\` header. The page then asks for the same file as a module script,
  which the platform always fetches in CORS mode, so *that* request does carry
  one. Any server answering with \`Vary: Origin\` - Vite's preview server does,
  and it is a common CDN default - makes the two non-equivalent, and every
  cache lookup misses. The app then serves its cached \`index.html\` offline and
  fails to load a single script: a blank page with a correct title, which looks
  like the app is broken rather than like the cache is.

  Safe, because every precached name is content-hashed: the URL determines the
  bytes, so there is nothing for a response to vary *by*.
*/
const MATCH = { ignoreVary: true };
const PRECACHE = ${JSON.stringify(precache, null, 2).replace(/\n/g, '\n')};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      /*
        Each file added on its own rather than through \`addAll\`, which rejects
        the whole install if any single request fails. One missing asset should
        cost that asset, not the entire offline mode.
      */
      Promise.all(
        PRECACHE.map((path) =>
          cache.add(new Request(path, { cache: 'reload' })).catch(() => {}),
        ),
      ),
    ),
  );
  // Deliberately no skipWaiting(): the page decides when to swap. See the
  // header of scripts/build-sw.mjs.
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith('forge-and-fate-') && name !== CACHE)
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

/** The page asks for this when the reader accepts an update. */
self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  /*
    Navigations go to the network first so an online visitor is never a deploy
    behind, and fall back to the cached page when there is nothing to reach.
    \`request.mode === 'navigate'\` rather than a Accept-header sniff, because
    that is what the request actually says it is.
  */
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
          return response;
        })
        .catch(() =>
          caches
            .match(request, MATCH)
            .then((hit) => hit ?? caches.match('index.html', MATCH))
            .then((hit) => hit ?? Response.error()),
        ),
    );
    return;
  }

  /*
    Everything else is cache-first, which is safe precisely because the names
    are content-hashed: \`data-r64-ROGa.js\` is that build's data chunk forever,
    so a hit can never be stale. A miss falls through to the network and is
    kept, which covers the lazily loaded chunks on a build where precaching one
    of them failed.
  */
  event.respondWith(
    caches.match(request, MATCH).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
          }
          return response;
        }),
    ),
  );
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
const bytes = (await stat(join(DIST, 'sw.js'))).size;
console.log(`  sw    ${precache.length} files precached, build ${buildId} (${bytes} B)`);
