#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Run from the repo root: the deploy stage needs relay/wrangler.toml.
if [[ ! -f relay/wrangler.toml ]]; then
  warn "run this from the Forge-Fate repo root (relay/wrangler.toml not found)"
  exit 1
fi

# Node lives at C:\Program Files\nodejs on this machine but is not always on
# Git Bash's PATH; put it there so npx works regardless of which shell this
# runs in.
if ! command -v npx >/dev/null 2>&1 && [[ -d "/c/Program Files/nodejs" ]]; then
  export PATH="/c/Program Files/nodejs:$PATH"
fi

banner "Forge-Fate relay: Cloudflare Worker (free tier)"

# ── Stage 1: a Cloudflare account ─────────────────────────────────────────
stage "Cloudflare account"
say "The relay runs as a Cloudflare Worker. The free plan covers a table's"
say "worth of traffic; no card is needed."
open_url "https://dash.cloudflare.com/login"
step "Log in, or create an account (Sign up on that page) and verify the email."
step "Land on the dashboard home. No plan upgrade, nothing else to configure."
pause "Logged in to the Cloudflare dashboard? Press Enter."

# ── Stage 2: wrangler, via npx ────────────────────────────────────────────
stage "Wrangler, Cloudflare's CLI"
say "No global install: npx fetches wrangler on first use and caches it."
if ! command -v npx >/dev/null 2>&1; then
  warn "npx is not on PATH in this shell. Open a terminal where 'node -v'"
  warn "works and re-run this wizard there."
  exit 1
fi
say "Checking wrangler (first run downloads it, ~30s)..."
npx -y wrangler@4 --version
pause "Wrangler printed a version? Press Enter."

# ── Stage 3: log wrangler in (browser OAuth) ──────────────────────────────
stage "Connect wrangler to your account"
say "This opens a browser page asking to authorize Wrangler."
step "Click 'Allow' on the page that opens, then come back here."
npx -y wrangler@4 login
say "Confirming who wrangler thinks you are:"
npx -y wrangler@4 whoami
pause "Does whoami show your account? Press Enter."

# ── Stage 4: deploy the relay ─────────────────────────────────────────────
stage "Deploy the relay"
say "Deploying relay/worker.js as 'forge-fate-relay'."
note "First deploy may ask you to register a free workers.dev subdomain —"
note "answer the prompt in this terminal, any name you like; it becomes part"
note "of the relay URL."
DEPLOY_LOG=$(mktemp)
( cd relay && npx -y wrangler@4 deploy 2>&1 | tee "$DEPLOY_LOG" )
WORKER_HTTPS=$(grep -oE 'https://[a-zA-Z0-9.-]+\.workers\.dev' "$DEPLOY_LOG" | head -n1 || true)
if [[ -n "$WORKER_HTTPS" ]]; then
  say "Deployed at: $WORKER_HTTPS"
else
  step "Copy the https://...workers.dev URL wrangler printed above."
  ask WORKER_HTTPS "Paste the worker URL (https://...):"
fi
RELAY_WSS="wss://${WORKER_HTTPS#https://}"
say "The app's relay URL is the same address as a websocket:"
say "  $RELAY_WSS"
pause "Press Enter to verify it answers."

# ── Stage 5: verify, and record the URL ───────────────────────────────────
stage "Verify and record"
say "A plain HTTPS request to the worker should get 426 ('expected a"
say "websocket') — that proves the room is live and routing."
CODE=$(curl -s -o /dev/null -w '%{http_code}' "${WORKER_HTTPS}/?room=TEST" || echo "no-answer")
if [[ "$CODE" == "426" ]]; then
  say "${GREEN}✓ 426 — the relay is up.${RESET}"
else
  warn "expected 426, got: $CODE. Give Cloudflare a minute and re-run this"
  warn "stage, or check the worker's logs in the dashboard (Workers & Pages"
  warn "→ forge-fate-relay → Logs)."
fi
# Recorded here only as a note-to-self; nothing in the build reads it. The
# app itself remembers the URL after the DM enters it once.
write_env FORGE_FATE_RELAY_URL "$RELAY_WSS"
say ""
say "Where it goes in the app:"
step "Open the battle screen → Prep drawer → 'The table'."
step "Paste $RELAY_WSS as the relay URL and press 'Open the table'."
step "Hand each player their seat link — it carries room, relay and seat."
note "The app remembers the relay URL on that device after the first time."
# ──────────────────────────────────────────────────────────────────────────

finish
say "Relay URL (keep it handy): $RELAY_WSS"
say "If you tell your agent this URL, it can pin it in relay/README.md."
